//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCBEntities : DbContext
    {
        public DCBEntities()
            : base("name=DCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detali> Detali { get; set; }
        public virtual DbSet<Fillial> Fillial { get; set; }
        public virtual DbSet<Oblast> Oblast { get; set; }
        public virtual DbSet<OrgType> OrgType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TerminalInf> TerminalInf { get; set; }
        public virtual DbSet<TerminalLocation> TerminalLocation { get; set; }
        public virtual DbSet<TerminalStatus> TerminalStatus { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<ZayavkaAction> ZayavkaAction { get; set; }
        public virtual DbSet<ZayavkaOtvet> ZayavkaOtvet { get; set; }
        public virtual DbSet<ZayavkaStatus> ZayavkaStatus { get; set; }
        public virtual DbSet<GetTerminalLocationWithAddress> GetTerminalLocationWithAddress { get; set; }
    }
}
