//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalLocation
    {
        public int Id { get; set; }
        public Nullable<int> IdTerminal { get; set; }
        public Nullable<float> Longth { get; set; }
        public Nullable<float> Width { get; set; }
    
        public virtual TerminalInf TerminalInf { get; set; }
    }
}
