//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalInf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerminalInf()
        {
            this.TerminalLocation = new HashSet<TerminalLocation>();
        }
    
        public int Id { get; set; }
        public int IdOblast { get; set; }
        public int IdFilial { get; set; }
        public Nullable<int> NomerTerminal { get; set; }
        public Nullable<int> Shtrihkod { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdTypeOrg { get; set; }
        public string NameOrg { get; set; }
        public string Address { get; set; }
        public Nullable<int> SummArenda { get; set; }
        public string Comment { get; set; }
    
        public virtual Fillial Fillial { get; set; }
        public virtual Oblast Oblast { get; set; }
        public virtual OrgType OrgType { get; set; }
        public virtual TerminalStatus TerminalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalLocation> TerminalLocation { get; set; }
    }
}
