//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkaOtvet
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Data { get; set; }
        public int IdZayavka { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdAction { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Zayavka Zayavka { get; set; }
        public virtual ZayavkaAction ZayavkaAction { get; set; }
        public virtual ZayavkaStatus ZayavkaStatus { get; set; }
    }
}
