//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavka()
        {
            this.ZayavkaOtvet = new HashSet<ZayavkaOtvet>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Data { get; set; }
        public int IdOblast { get; set; }
        public int IdFilial { get; set; }
        public int IdDetal { get; set; }
        public string Comment { get; set; }
    
        public virtual Detali Detali { get; set; }
        public virtual Fillial Fillial { get; set; }
        public virtual Oblast Oblast { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaOtvet> ZayavkaOtvet { get; set; }
    }
}
